export const randomData = {
  currentPage: 1,
  hasNextPage: false,
  results: [
    {
      id: "16526",
      malId: 16526,
      title: {
        romaji: "Ranpou",
        english: null,
        native: "らんぽう",
        userPreferred: "Ranpou",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16526-uD2D5BgXVsGv.jpg",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 203,
      description:
        'TV anime adaptation of Masatoshi Uchizaki\'s gag comedy manga "Ranpou".',
      rating: null,
      genres: ["Comedy"],
      color: "#43bbe4",
      totalEpisodes: 21,
      currentEpisodeCount: 21,
      type: "TV",
      releaseDate: 1984,
    },
    {
      id: "16001",
      malId: 16001,
      title: {
        romaji: "Kokoro Connect: Michi Random",
        english: "Kokoro Connect ~ The OVAs",
        native: "ココロコネクト ミチランダム",
        userPreferred: "Kokoro Connect: Michi Random",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16001-XLc5ZdWeM3fp.png",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16001-DDirBT9iSrGs.jpg",
      coverHash: "hash",
      popularity: 48976,
      description:
        "They've already had their bodies swapped like musical chairs, had their ages changed at random and experienced their deepest desires taking control of them without warning, but if you thought Heartseed was finished with Taichi, Iori, Himeko, Yoshifumi and Yui, you've got another thing coming! Now there's a new affliction going around, and the name of this peculiar bug is emotion sickness. As in, suddenly your emotions jump out of your body and sick someone else! Needless to say, that's more than simply awkward if you've got a deep rooted phobia like a fear of men or repressed emotions that you've been trying to keep hidden, but in some situations it can literally be deadly! What is Heartseed up to this time, and why is he making our heroes involuntarily share their innermost dirty laundry?<br>\n<br>\n(Source: Sentai Filmworks)",
      rating: 76,
      genres: ["Drama", "Romance", "Slice of Life", "Supernatural"],
      color: "#866b28",
      totalEpisodes: 4,
      currentEpisodeCount: 4,
      type: "OVA",
      releaseDate: 2012,
    },
    {
      id: "118639",
      malId: 37532,
      title: {
        romaji: "Random (web edit ver.)",
        english: "Random (web edit ver.)",
        native: "ランダム（web edit ver.）",
        userPreferred: "Random (web edit ver.)",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b118639-lRBlHm4qyeyH.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/118639-RC5GqBmeRXQW.jpg",
      coverHash: "hash",
      popularity: 119,
      description:
        "Official music video for Handsome Kenya's song Random which was on his 1st full album titled \"Amnesia\" that was released March 5, 2014. A special extended version of the music video was created for the web release on Victor Entertainment's official YouTube channel. In it, Handsome Kenya falls asleep on a weekly manga magazine and dreams that he's stuck inside the volume as he runs between all the different series, art styles, and scenarios.",
      rating: 45,
      genres: [],
      color: null,
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "MUSIC",
      releaseDate: null,
    },
    {
      id: "103958",
      malId: 37816,
      title: {
        romaji: "Bandoe Sareoriratda",
        english: "I'll Just Live In Bando",
        native: "반도에 살어리랏다",
        userPreferred: "Bandoe Sareoriratda",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx103958-54dbPvZFG4lw.png",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 130,
      description:
        "46-year-old Oh Jun-Koo struggles between following his dreams of becoming an actor and focusing on his teaching career to support his family.<br>\n<br>\n<i>Debuted at the 2017 Annecy International Animation Film Festival</i>",
      rating: null,
      genres: ["Comedy", "Drama", "Slice of Life"],
      color: "#e4d693",
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "MOVIE",
      releaseDate: null,
    },
    {
      id: "102451",
      malId: 33281,
      title: {
        romaji: "Mori no Andou",
        english: "Ando of the Woods",
        native: "森の安藤",
        userPreferred: "Mori no Andou",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/102451-YNKeZN6HREIR.jpg",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 1153,
      description:
        'A penguin named Andou protects the forest and its animal inhabitants from the evil humans (or the "cancer of the Earth" as one sign in The Animal House reads). However, some of the animals suspect that Ando himself may be a human.',
      rating: 49,
      genres: ["Comedy"],
      color: "#f1e4ae",
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "ONA",
      releaseDate: null,
    },
    {
      id: "113023",
      malId: 40665,
      title: {
        romaji: "Shoujo☆Kageki Revue Starlight: Rondo Rondo Rondo",
        english: null,
        native: "少女☆歌劇 レヴュースタァライト ロンド・ロンド・ロンド",
        userPreferred: "Shoujo☆Kageki Revue Starlight: Rondo Rondo Rondo",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113023-ppUSdBgb9pzc.jpg",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 4081,
      description: "A compilation film recapping the anime series.",
      rating: 76,
      genres: ["Action", "Drama", "Music"],
      color: "#50a1e4",
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "MOVIE",
      releaseDate: 2020,
    },
    {
      id: "143389",
      malId: 53157,
      title: {
        romaji: "Nando Demo Wasureyoo",
        english: "Keep Forgetting",
        native: "何度でも忘れよう",
        userPreferred: "Nando Demo Wasureyoo",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143389-6BYL098aIUWZ.jpg",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 90,
      description:
        "Why do you want acceptance? If it's not going to happen, then forget about what it was you wanted acknowledged and just have some soup, like always.\n<br><br>\nGraduate Work 2019, Tokyo University of the Arts, Graduate School of Film and New Media, Department of Animation\n<br><br>\n(Source: Geidai Animation)",
      rating: null,
      genres: ["Horror", "Psychological"],
      color: null,
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "MOVIE",
      releaseDate: null,
    },
    {
      id: "122187",
      malId: 41296,
      title: {
        romaji: "VALHAIT RISING: Kandou e.",
        english: null,
        native: "VALHAIT RISING 『感動へ。』",
        userPreferred: "VALHAIT RISING: Kandou e.",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx122187-2lgNGo5ZtcyN.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/122187-P9H9G6kdys7n.jpg",
      coverHash: "hash",
      popularity: 225,
      description:
        "Studio Colorido's promotional video for BANDAI NAMCO Online's mobile RPG VALHAIT RISING. VALHAIT RISING was released for Android and iOS and ran from July 27, 2016 to April 13, 2017.",
      rating: 49,
      genres: ["Action", "Adventure", "Fantasy"],
      color: "#f1d635",
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "ONA",
      releaseDate: null,
    },
    {
      id: "104631",
      malId: 31252,
      title: {
        romaji: "Korekarasaki, Nando Anata to.",
        english: null,
        native: "これから先, 何度あなたと.",
        userPreferred: "Korekarasaki, Nando Anata to.",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/n104631-hViOrNVKOMFG.jpg",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 434,
      description:
        'Animated music video for mishmash＊Aimee Isobe\'s "Korekarasaki, Nando Anata to."',
      rating: 52,
      genres: ["Slice of Life"],
      color: "#5dbbf1",
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "MUSIC",
      releaseDate: null,
    },
    {
      id: "20806",
      malId: 25731,
      title: {
        romaji: "Cross Ange: Tenshi to Ryuu no Rondo",
        english: "Cross Ange: Rondo of Angel and Dragon",
        native: "クロスアンジュ 天使と竜の輪舞",
        userPreferred: "Cross Ange: Tenshi to Ryuu no Rondo",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20806-TFTl8bavYzvc.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/n20806-rXk0tGTLIehi.jpg",
      coverHash: "hash",
      popularity: 38391,
      description:
        "Betrayed, stripped of her birthright, and declared less than human. Everything that Princess Angelise Ikaruga Misurugi of the Misurugi Empire thought she knew about her world was a lie. Now, for the crime of not being able to use magic, she’s been sentenced to certain death as a slave-soldier. The girl now known as Ange is no longer an innocent Princess: she’s learning how to kill draconic invaders, defending the same traitors who stole her life. However, they made a fatal mistake: they gave her access to an incredible weapon.<br>\n<br>\n(Source: Sentai Filmworks)",
      rating: 69,
      genres: ["Action", "Ecchi", "Mecha", "Romance", "Sci-Fi"],
      color: "#f1d650",
      totalEpisodes: 25,
      currentEpisodeCount: 25,
      type: "TV",
      releaseDate: 2014,
    },
    {
      id: "101812",
      malId: 34439,
      title: {
        romaji: "Code Geass: Hangyaku no Lelouch II - Handou",
        english: "Code Geass: Lelouch of the Rebellion II - Transgression",
        native: "コードギアス 反逆のルルーシュⅡ 叛道",
        userPreferred: "Code Geass: Hangyaku no Lelouch II - Handou",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101812-rCTRQhzHIryT.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101812-Eeeg4HxYwc2i.jpg",
      coverHash: "hash",
      popularity: 19394,
      description:
        "Second of the three part theatrical film remake of Code Geass: Lelouch of the Rebellion and Code Geass: Lelouch of the Rebellion R2.",
      rating: 73,
      genres: [
        "Action",
        "Mecha",
        "Romance",
        "Sci-Fi",
        "Supernatural",
        "Thriller",
      ],
      color: "#f1e45d",
      totalEpisodes: 1,
      currentEpisodeCount: 1,
      type: "MOVIE",
      releaseDate: 2018,
    },
    {
      id: "3807",
      malId: 3807,
      title: {
        romaji: "Honoo no Alpen Rose: Judy & Randy",
        english: "Alpen Rose",
        native: "炎のアルペンローゼ・ジュディ＆ランディ",
        userPreferred: "Honoo no Alpen Rose: Judy & Randy",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx3807-uRtS1pueVvmG.png",
      imageHash: "hash",
      cover: null,
      coverHash: "hash",
      popularity: 1263,
      description:
        "While Randy was walking through the Swiss countryside he finds a small girl, who seemed to be the only survived person from an airplane crash. The little girl didn&rsquo;t remember anything, and Randy decided to take care of her and he called her Judy. The both go their childhood together. A few years later, Judy, now 16 years old, wants to find her past. With the help of Randy, she leaves to research her origins. Her single clue is a song that she keeps hearing in her head, the song is called Alpine Rose. At a time of world war, these two young people will have to overcome many obstacles to arrive at their goal in this time of war, with having only each other to comfort and support. the depth of their love.<br><br>\n(Source: Anime News Network)",
      rating: 61,
      genres: ["Drama", "Romance"],
      color: "#f16b0d",
      totalEpisodes: 20,
      currentEpisodeCount: 20,
      type: "TV",
      releaseDate: 1985,
    },
    {
      id: "3712",
      malId: 3712,
      title: {
        romaji: "Zero no Tsukaima: Princesses no Rondo",
        english: 'The Familiar of Zero: "Rondo" of Princesses',
        native: "ゼロの使い魔 ～三美姫（プリンセッセ）の輪舞（ロンド）～",
        userPreferred: "Zero no Tsukaima: Princesses no Rondo",
      },
      status: "Completed",
      image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx3712-zt0ac4fjixWl.jpg",
      imageHash: "hash",
      cover:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/3712-Ji7NQXtiVrV8.jpg",
      coverHash: "hash",
      popularity: 60285,
      description:
        "Following Saito's heroic actions in the War with Albion in season two, Saito &amp; Louise return to Tristain, only to have the runes which bind Saito &amp; Louise disappear. Saito &amp; Louise struggle with a relationship no longer defined as Master &amp; Familiar, as they search for an Elf who has the power to restore the dead to life, and may hold the key to understanding Saito's loss of the Gandalfr's power.\n<br><br>\n(Source: Anime News Network)",
      rating: 69,
      genres: ["Action", "Adventure", "Comedy", "Ecchi", "Fantasy", "Romance"],
      color: "#e41a78",
      totalEpisodes: 12,
      currentEpisodeCount: 12,
      type: "TV",
      releaseDate: 2008,
    },
  ],
};
